spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
    suffix: .html
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: 'true'
        show_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password: '0000'
    username: 'fitflow'
    url: jdbc:mariadb://fitflow.co1hyn5ouefl.ap-northeast-1.rds.amazonaws.com:3306/fitflow?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul;
  profiles:
    include: oauth0p;
  data:
    rest:
      basePath: /api
server:
  port: 8080
jwt:
  secret: aksueaobhieaipgagiohagnjaslqmbozsejmaskasdgrwg
  access-token-expire-time: 1800000
  refresh-token-expire-time: 2592000000