spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
    suffix: .html
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: 'true'
        show_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password: '0000'
    username: 'fitflowdev'
    url: jdbc:mariadb://35.79.8.201:3306/fitflow
  profiles:
    include: oauth0p;
  data:
    rest:
      basePath: /api
server:
  port: 8080
jwt:
  secret: aksueaobhieaipgagiohagnjaslqmbozsejmaskasdgrwg
  access-token-expire-time: 1800000
  refresh-token-expire-time: 2592000000